@startuml

object race
object horse
object bettor
object bet

object horseRace
object horseBet

race --|{ bet
bettor --|{ bet

race --|{ horseRace
horse --|{ horseRace

bet--|{ horseBet
horse --|{ horseBet

@enduml