@startuml
object hippodrome
object race
object horse
object bettor
object bet
object betState
object raceResult
object betResult
object betAmount
object horsesOrder
object verifyBet
object calculateResult
object acction

hippodrome o-- "n"race
race *-- "10"horse
race *-- "n"bettor
race*-- "n"bet

bet *-- betState
bet *-- betAmount
bet *-- horsesOrder

race *-- acction

race *-- raceResult
bet *-- betResult

acction <|--verifyBet
acction <|--calculateResult

bettor --> bet

bet--> horse

horsesOrder *-- horse
@enduml